In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Shipping_Delay_Dataset_with_Missing_Values.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Shipping_Method    450 non-null    object
 1   Weather_Condition  450 non-null    object
 2   Region             450 non-null    object
 3   Product_ID         500 non-null    object
 4   Courier            450 non-null    object
 5   Priority_Level     450 non-null    object
 6   Estimated_Days     450 non-null    float64
 7   Actual_Days        450 non-null    float64
 8   Delay_Days         500 non-null    int64
dtypes: float64(2), int64(1), object(6)
memory usage: 35.3+ KB

In [8]:
print(df.isnull().sum()

Shipping_Method      50
Weather_Condition    50
Region               50
Product_ID            0
Courier              50
Priority_Level       50
Estimated_Days       50
Actual_Days          50
Delay_Days            0
dtype: int64

In [6]:
df['Priority_Level'].unique()

array(['Medium', 'Critical', 'High', 'Low', nan], dtype=object)

In [9]:
from sklearn.impute import SimpleImputer

In [18]:
numerical_features = ["Estimated_Days", "Actual_Days"]
categorical_features = ["Shipping_Method", "Weather_Condition", "Region", "Courier", "Priority_Level"]

In [22]:
num_imputer=SimpleImputer(strategy='median')
df[numerical_features]=num_imputer.fit_transform(df[numerical_features])

cat_imputer=SimpleImputer(strategy='most_frequent')
df[categorical_features]=cat_imputer.fit_transform(df[categorical_features])

In [25]:
from sklearn.preprocessing import OneHotEncoder

In [38]:
ohe=OneHotEncoder(handle_unknown='ignore',sparse_output=False).set_output(transform='pandas')

In [39]:
df

,Shipping_Method,Weather_Condition,Region,Product_ID,Courier,Priority_Level,Estimated_Days,Actual_Days,Delay_Days
0,Same-Day,Stormy,South,Product_51,Amazon Logistics,Medium,3.000000,12.0,9
1,Overnight,Clear,East,Product_70,DHL,Medium,2.000000,7.5,10
2,Standard,Clear,North,Product_6,USPS,Critical,9.000000,9.0,0
3,Same-Day,Snowy,North,Product_67,Amazon Logistics,Medium,2.000000,11.0,9
4,Same-Day,Stormy,North,Product_7,DHL,Medium,5.128889,7.5,0
...,...,...,...,...,...,...,...,...,...
495,Overnight,Clear,North,Product_14,DHL,High,4.000000,6.0,2
496,Same-Day,Clear,North,Product_30,UPS,High,6.000000,7.5,5
497,Overnight,Snowy,West,Product_68,Amazon Logistics,High,2.000000,11.0,9
498,Standard,Snowy,East,Product_18,Amazon Logistics,High,6.000000,10.0,4
499,Overnight,Stormy,East,Product_62,USPS,Low,3.000000,3.0,0

In [44]:
df['Shipping_Method']

0       Same-Day
1      Overnight
2       Standard
3       Same-Day
4       Same-Day
         ...
495    Overnight
496     Same-Day
497    Overnight
498     Standard
499    Overnight
Name: Shipping_Method, Length: 500, dtype: object

In [46]:
ohe_transformed_df=ohe.fit_transform(df[['Shipping_Method','Weather_Condition','Region','Courier']])

In [47]:
ohe_transformed_df

,Shipping_Method_Express,Shipping_Method_Overnight,Shipping_Method_Same-Day,Shipping_Method_Standard,Weather_Condition_Clear,Weather_Condition_Rainy,Weather_Condition_Snowy,Weather_Condition_Stormy,Region_East,Region_North,Region_South,Region_West,Courier_Amazon Logistics,Courier_DHL,Courier_FedEx,Courier_UPS,Courier_USPS
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
496,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
497,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
498,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
499,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [49]:
df=pd.concat([df,ohe_transformed_df],axis=1).drop(columns=['Shipping_Method','Weather_Condition','Region','Courier'])

In [50]:
df

,Product_ID,Priority_Level,Estimated_Days,Actual_Days,Delay_Days,Shipping_Method_Express,Shipping_Method_Overnight,Shipping_Method_Same-Day,Shipping_Method_Standard,Weather_Condition_Clear,...,Weather_Condition_Stormy,Region_East,Region_North,Region_South,Region_West,Courier_Amazon Logistics,Courier_DHL,Courier_FedEx,Courier_UPS,Courier_USPS
0,Product_51,Medium,3.000000,12.0,9,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1,Product_70,Medium,2.000000,7.5,10,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,Product_6,Critical,9.000000,9.0,0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,Product_67,Medium,2.000000,11.0,9,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,Product_7,Medium,5.128889,7.5,0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Product_14,High,4.000000,6.0,2,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
496,Product_30,High,6.000000,7.5,5,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
497,Product_68,High,2.000000,11.0,9,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
498,Product_18,High,6.000000,10.0,4,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
499,Product_62,Low,3.000000,3.0,0,0.0,1.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [51]:
from sklearn.preprocessing import OrdinalEncoder

In [52]:
df['Priority_Level'].unique()

array(['Medium', 'Critical', 'High', 'Low'], dtype=object)

In [57]:
size=['Low','Medium','High','Critical']

In [58]:
enc=OrdinalEncoder(categories=[size])

In [60]:
df['Priority_Level']=enc.fit_transform(df[['Priority_Level']])

In [62]:
len(df['Product_ID'].unique())

99